workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tom728.biztimer

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Build iOS
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    integrations:
      app_store_connect: codemagic

    publishing:
      app_store_connect:
        auth: integration