workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60

    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.tom728.biztimer

    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_IDENTIFIER" \
            --type IOS_APP_STORE \
            --create
          keychain add-certificates
          xcode-project use-profiles

      - name: Build IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/Runner.xcworkspace \
            --scheme Runner

    artifacts:
      - build/ios/ipa/*.ipa

    integrations:
      app_store_connect: codemagic

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true